name: 'Lint Code'
description: 'Run all linters (Python, Shell, Markdown, YAML, Batch)'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Python linting dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black pylint mypy types-python-dateutil

    - name: Run flake8
      shell: bash
      run: |
        flake8 mouse_keepalive/ --max-line-length=120 --extend-ignore=E203,W503

    - name: Run black (check)
      shell: bash
      run: |
        black --check --line-length=120 mouse_keepalive/

    - name: Run pylint
      shell: bash
      run: |
        pylint mouse_keepalive/ --max-line-length=120 --disable=C0111 || true

    - name: Run mypy (type checking)
      shell: bash
      run: |
        mypy mouse_keepalive/ --ignore-missing-imports || true

    - name: Install ShellCheck
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck

    - name: Run ShellCheck
      shell: bash
      run: |
        shellcheck move_mouse.sh || true

    - name: Install markdownlint-cli
      shell: bash
      run: |
        npm install -g markdownlint-cli

    - name: Run markdownlint
      shell: bash
      run: |
        markdownlint "*.md" --config .markdownlint.json || true

    - name: Install yamllint
      shell: bash
      run: |
        pip install yamllint

    - name: Run yamllint
      shell: bash
      run: |
        yamllint -c .yamllint.yml .github/workflows/*.yml || true

    - name: Check batch script syntax (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        # Basic syntax check for batch files
        Write-Host "Checking batch script syntax..."
        Select-String -Path move_mouse.bat -Pattern "@echo off" | Out-Null
        if ($LASTEXITCODE -ne 0) { exit 1 }
        Write-Host "Batch script syntax check passed"

